### ISSUE TITLE
Conduct synthesis for Sprint 4 Usability Research

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#110]
### Task
Synthesize what we learned in Sprint 4.

### Details / Context
This can be high-level, but we need to synthesize both at the individual research session level, and across all interviews.

### Acceptance Criteria
- [x] all interviews have been debriefed with the appropriate members of the Nava team
- [x] synthesis framework created
- [x] synthesis conducted
- [x] research debrief internally
- [ ] findings documented in an artifact that can be shared externally

**Comment by AngelQuicksey** [comment]
@nguyen-tina I'm updating the acceptance criteria here. We probably won't be affinity-mapping toward high level themes for this type of research. We'll need a different kind of synth framework that will loop our findings back into the design. Happy to explain more in braintime or our 1:1

**Comment by AngelQuicksey** [comment]
@AngelQuicksey to schedule time to pair on synth framework with @nguyen-tina and @nicoleslaw  in order to begin synthesizing findings.

**Comment by nicoleslaw** [comment]
Tina and I met this afternoon and categorized our findings and user quotes. Next, we'd like to review these internally and draft any related user stories as a team before prepping the research for EDD.

**Comment by nguyen-tina** [comment]
I took a shot at drafting many user stories. We can review these and pick up from here (what's the requirements from these stories).

**Comment by nicoleslaw** [comment]
I wrote a summary of our findings today and we'll discuss internally before sharing out.

**Comment by nicoleslaw** [comment]
In discussion, we will roll our findings into a new iteration. I will make a new ticket for that work.
