### ISSUE TITLE
Update designs for time-out modal

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#111]
### Task
How should the time-out warning function and look like?

### Details / Context
The time-out warning function needs to be mobile and desktop friendly.

### Acceptance Criteria
- [ ] Mobile designs are created
- [ ] Desktop designs are created
- [ ] Review designs with engineering

**Comment by nicoleslaw** [comment]
Can we close this out for now?

**Comment by nguyen-tina** [comment]
Yes, we can open a new ticket whenever it's necessary
