### ISSUE TITLE
Develop North Star prototype to higher fidelity

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#120]
### Task
Develop the North Start prototype to understand how the full Claim Tracker could address and solve claimant issues surfaced in the Discovery phase.

### Details / Context
During the Discovery phase of the Claim Tracker project, research participants vocalized many desires that were not limited to only knowing where their claim was in the lifecycle. 

### Acceptance Criteria

- [x] Explore what the Claim Activity page would look like
- [ ] Explore what the Certification Activity page would look like
- [ ] Within the Certification Activity page, demonstrate how each week would show an evolving status
