### ISSUE TITLE
Create proposal to update header to match EDD's Global Header

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/ui-claim-tracker#195]
### Task
Create proposal for updating the minimal header to one that matches v2.1, which EDD will ship starting 6/1.

### Details / Context
Explain why we have the header that we do today, and how we are proposing it change.

### Acceptance Criteria

- [x] Proposal is written
- [x] Proposal includes screenshots 
- [x] Proposal is reviewed by Nicole
- [x] Proposal is reviewed by Diana and Kalvin

**Comment by nguyen-tina** [comment]
Closing this ticket, next step is to review with PM about how to move forward with this when client is ready
