### ISSUE TITLE
Create and execute S4 recruitment plan

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#22]
### Task
Prepare to conduct outreach and create pool of screened users to test with for both rounds 1 & 2

### Details / Context
Research participants need to have used the unemployment system within the past year (January 2020 - present). Ideally, we would recruit from a wide variety of dis/abilities and language.

### Acceptance Criteria

Recruitment
- [x] Participant pool and sample criteria is developed
- [x] Screener finalized 
- [x] Channels for outreach identified
- [x] Write email to follow up for participants from existing database
- [x] Send email to participants
- [x] Write Craigslist Posting
- [ ] Post Craigslist call for May research

**Comment by nguyen-tina** [comment]
Since S4 research has completed, I'm going to move the open call for screening to the next research recruitment ticket once the second round of research details has been finalized.
