### ISSUE TITLE
Define roadmap/work plan and dependencies for remaining MVP releases

### ISSUE THREAD

**Issue by dianagriffin** [cagov/ui-claim-tracker#225]
### Description

Define and document the work and dependencies needed to meet planned milestones and releases to deliver the full MVP.

### Acceptance Criteria

- [ ] Roadmap/work plan and associated dependencies are documented
- [ ] Roadmap/work plan have been reviewed with the Nava team
- [ ] Roadmap/work plan have been reviewed with EDD
