### ISSUE TITLE
Integrate Final Content into the Claim Tracker Application

### ISSUE THREAD

**Issue by lomky** [cagov/ui-claim-tracker#329]
### Description

As we are finalizing the content for the initial release, work with Content to get the final strings into the application

### Acceptance Criteria

- [ ] Final English strings are in the application
  - [ ] Common strings
  - [ ] scenario specific strings
- [ ] Translated strings are in the application

**Comment by kalvinwang** [comment]
@rocketnova oops didn't see you just self-assigned it! anyway i think i'm updating it accurately
