### ISSUE TITLE
Develop CA UI Design Brief for 2021 Claim Tracker MVP

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#68]
### Description
This should be the design companion to the technical planning doc. It will highlight the design workstreams, open questions, and high-level design direction. 

### Acceptance Criteria

  - [x] Draft design workstreams
  - [x] Document open questions
  - [x] Document high-level design direction and assumptions
  - [x] Draft timeline & milestones
  - [x] Share with team for feedback
  - [x] Finalize

**Comment by AngelQuicksey** [comment]
[2021 Claim Tracker MVP – Design Brief](https://docs.google.com/document/d/1qd5ck77JOImypUFOBjKBaACFyH8lWAd6uLf1ZqwflQE/edit#heading=h.ib401qkw3q1n)
[WIP / Design roadmap](https://docs.google.com/spreadsheets/d/1xqCyGbiCDhrSY8FxkXXpnlScIBFI29cNHZ893UNtIrQ/edit#gid=249271923)
